version: '3'

services:
  redis:
    container_name: 'redis'
    image: 'redis:4.0.10-alpine'

  laravel-echo:
    image: 'vieiram2/laravel-echo-server:1.3.2'
    container_name: 'laravel-echo-server'
    ports:
      - '6001:6001'
    links:
      - 'redis:redis'
    volumes:
      - laravel-echo-server.json:/app/laravel-echo-server.json:ro
